### ISSUE TITLE
Build process is not parallel jobs safe?

### ISSUE THREAD

**Issue by danfe** [Softmotions/iwnet#2]
We're seeing consistent failures on our FreeBSD package build cluster.  It looks like there is a race when `generated_mimegen.h` is being created by two commands simultaneously.  I'm attaching the full [build log](https://github.com/Softmotions/iwnet/files/8644480/iwnet-g20220223.log) in case you want to take a closer look.

**Comment by adamansky** [comment]
I've removed `USES_TERMINAL` from `add_custom_command` in `tools/CMakeLists.txt` it may infers with Ninja jobs configuration but I'm not sure, since cannot reproduce your problem with ninja  `1.10.0`

**Comment by adamansky** [comment]
Thank you @danfe!
